#!/bin/sh

# 11:30:48 02/16/2017.  Didn't use this to generate my policy file, but,
# I experimented with it.

java -cp "/root/apbin/Pro-Grade/pro-grade-master/target/pro-grade.jar":"/root/apbin/VUE/VUE.jar" \
-Djava.security.manager=net.sourceforge.prograde.sm.PolicyFileGeneratorJSM \
-Dprograde.generated.policy=/tmp/For_VUE---generated.java.policy \
tufts.vue.VUE \
"/root/apmaps/Maps/Testmap.vue" \
2>&1 | tee /tmp/Log---VUE_with_ProGrade_Policy_Generator.txt


# -Djava.security.policy=="/root/00-Construction/VUE/Apollia_Files/java.policy" \