#!/bin/sh

java -cp "/root/apbin/Pro-Grade/pro-grade-master/target/pro-grade.jar":"/root/apbin/VUE/VUE.jar" \
-Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM \
-Djava.security.debug="access,failure" \
-Djava.security.policy=="/root/00-Construction/VUE/Apollia_Files/java.policy" \
-DsocksProxyHost=127.0.0.1 \
tufts.vue.VUE \
"/root/apmaps/Maps/Testmap.vue" \
2>&1 | tee /tmp/Shorter_Debug_Log---VUE_With_Java_Policy.txt


# 12:21:17 02/16/2017.  This launcher results in a smaller, less informative debug log.
